version: "3.3"

services:
      
  orangehrm:
    image: orangehrm
    restart: unless-stopped
    ports:
      - "8200:80"
      - "8443:443"
    environment:
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_USER=root
      - ORANGEHRM_DATABASE_PASSWORD=orangehrm
      - ORANGEHRM_DATABASE_NAME=orangehrm
      - PUID=998
      - PGID=100
    volumes:
      - ./orange:/orangehrm